/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThreeWaysToWorkRouteImport } from './routes/three-ways-to-work'
import { Route as PromptEngineeringRouteImport } from './routes/prompt-engineering'
import { Route as McpConnectorsPluginsRouteImport } from './routes/mcp-connectors-plugins'
import { Route as ClaudeVsChatgptRouteImport } from './routes/claude-vs-chatgpt'
import { Route as ClaudeSkillsRouteImport } from './routes/claude-skills'
import { Route as ClaudeFeaturesRouteImport } from './routes/claude-features'
import { Route as ArtifactsVsExecutionRouteImport } from './routes/artifacts-vs-execution'
import { Route as IndexRouteImport } from './routes/index'

const ThreeWaysToWorkRoute = ThreeWaysToWorkRouteImport.update({
  id: '/three-ways-to-work',
  path: '/three-ways-to-work',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptEngineeringRoute = PromptEngineeringRouteImport.update({
  id: '/prompt-engineering',
  path: '/prompt-engineering',
  getParentRoute: () => rootRouteImport,
} as any)
const McpConnectorsPluginsRoute = McpConnectorsPluginsRouteImport.update({
  id: '/mcp-connectors-plugins',
  path: '/mcp-connectors-plugins',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaudeVsChatgptRoute = ClaudeVsChatgptRouteImport.update({
  id: '/claude-vs-chatgpt',
  path: '/claude-vs-chatgpt',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaudeSkillsRoute = ClaudeSkillsRouteImport.update({
  id: '/claude-skills',
  path: '/claude-skills',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaudeFeaturesRoute = ClaudeFeaturesRouteImport.update({
  id: '/claude-features',
  path: '/claude-features',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtifactsVsExecutionRoute = ArtifactsVsExecutionRouteImport.update({
  id: '/artifacts-vs-execution',
  path: '/artifacts-vs-execution',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/artifacts-vs-execution': typeof ArtifactsVsExecutionRoute
  '/claude-features': typeof ClaudeFeaturesRoute
  '/claude-skills': typeof ClaudeSkillsRoute
  '/claude-vs-chatgpt': typeof ClaudeVsChatgptRoute
  '/mcp-connectors-plugins': typeof McpConnectorsPluginsRoute
  '/prompt-engineering': typeof PromptEngineeringRoute
  '/three-ways-to-work': typeof ThreeWaysToWorkRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/artifacts-vs-execution': typeof ArtifactsVsExecutionRoute
  '/claude-features': typeof ClaudeFeaturesRoute
  '/claude-skills': typeof ClaudeSkillsRoute
  '/claude-vs-chatgpt': typeof ClaudeVsChatgptRoute
  '/mcp-connectors-plugins': typeof McpConnectorsPluginsRoute
  '/prompt-engineering': typeof PromptEngineeringRoute
  '/three-ways-to-work': typeof ThreeWaysToWorkRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/artifacts-vs-execution': typeof ArtifactsVsExecutionRoute
  '/claude-features': typeof ClaudeFeaturesRoute
  '/claude-skills': typeof ClaudeSkillsRoute
  '/claude-vs-chatgpt': typeof ClaudeVsChatgptRoute
  '/mcp-connectors-plugins': typeof McpConnectorsPluginsRoute
  '/prompt-engineering': typeof PromptEngineeringRoute
  '/three-ways-to-work': typeof ThreeWaysToWorkRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/artifacts-vs-execution'
    | '/claude-features'
    | '/claude-skills'
    | '/claude-vs-chatgpt'
    | '/mcp-connectors-plugins'
    | '/prompt-engineering'
    | '/three-ways-to-work'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/artifacts-vs-execution'
    | '/claude-features'
    | '/claude-skills'
    | '/claude-vs-chatgpt'
    | '/mcp-connectors-plugins'
    | '/prompt-engineering'
    | '/three-ways-to-work'
  id:
    | '__root__'
    | '/'
    | '/artifacts-vs-execution'
    | '/claude-features'
    | '/claude-skills'
    | '/claude-vs-chatgpt'
    | '/mcp-connectors-plugins'
    | '/prompt-engineering'
    | '/three-ways-to-work'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArtifactsVsExecutionRoute: typeof ArtifactsVsExecutionRoute
  ClaudeFeaturesRoute: typeof ClaudeFeaturesRoute
  ClaudeSkillsRoute: typeof ClaudeSkillsRoute
  ClaudeVsChatgptRoute: typeof ClaudeVsChatgptRoute
  McpConnectorsPluginsRoute: typeof McpConnectorsPluginsRoute
  PromptEngineeringRoute: typeof PromptEngineeringRoute
  ThreeWaysToWorkRoute: typeof ThreeWaysToWorkRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/three-ways-to-work': {
      id: '/three-ways-to-work'
      path: '/three-ways-to-work'
      fullPath: '/three-ways-to-work'
      preLoaderRoute: typeof ThreeWaysToWorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompt-engineering': {
      id: '/prompt-engineering'
      path: '/prompt-engineering'
      fullPath: '/prompt-engineering'
      preLoaderRoute: typeof PromptEngineeringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp-connectors-plugins': {
      id: '/mcp-connectors-plugins'
      path: '/mcp-connectors-plugins'
      fullPath: '/mcp-connectors-plugins'
      preLoaderRoute: typeof McpConnectorsPluginsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claude-vs-chatgpt': {
      id: '/claude-vs-chatgpt'
      path: '/claude-vs-chatgpt'
      fullPath: '/claude-vs-chatgpt'
      preLoaderRoute: typeof ClaudeVsChatgptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claude-skills': {
      id: '/claude-skills'
      path: '/claude-skills'
      fullPath: '/claude-skills'
      preLoaderRoute: typeof ClaudeSkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claude-features': {
      id: '/claude-features'
      path: '/claude-features'
      fullPath: '/claude-features'
      preLoaderRoute: typeof ClaudeFeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artifacts-vs-execution': {
      id: '/artifacts-vs-execution'
      path: '/artifacts-vs-execution'
      fullPath: '/artifacts-vs-execution'
      preLoaderRoute: typeof ArtifactsVsExecutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArtifactsVsExecutionRoute: ArtifactsVsExecutionRoute,
  ClaudeFeaturesRoute: ClaudeFeaturesRoute,
  ClaudeSkillsRoute: ClaudeSkillsRoute,
  ClaudeVsChatgptRoute: ClaudeVsChatgptRoute,
  McpConnectorsPluginsRoute: McpConnectorsPluginsRoute,
  PromptEngineeringRoute: PromptEngineeringRoute,
  ThreeWaysToWorkRoute: ThreeWaysToWorkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
